name: cool-dns
on:
  push: 
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Cool DNS docker image
      run: docker build .
